spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vectoria
    username: postgres
    password: 70304196

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

server:
  port: 8080
