spring:
  sql:
    init:
      mode: always     # F체hrt schema-manuel.sql bei jedem Start aus -> DB-INIT
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/vectoria
    username: postgres
    password: 70304196

  jpa:
    open-in-view: false   # false = Session nicht bis zum View offen halten (empfohlen f체r REST)
    # open-in-view: true  # explizit einschalten,um Lazy-Loading w채hrend des Renderns zu erlauben
    properties: {}            # leere Map statt leere String-Zeile
    hibernate:
      ddl-auto: update        # oder create-drop, f체r ein frisch Start der DB
server:
  port: 8080

vectoria:
  llm:
    base-url: http://localhost:4000
    api-key: dummy          # falls du im LiteLLM noch Auth einbaust
    chat-model: qwen-local-chat
    embedding-model: qwen-local-embed
