spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vectoria
    username: postgres
    password: 70304196

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

server:
  port: 8080

vectoria:
  llm:
    base-url: http://localhost:4000
    api-key: dummy          # falls du im LiteLLM noch Auth einbaust
    chat-model: qwen-local-chat
    embedding-model: qwen-local-embed
